### ISSUE TITLE
can you add auto-complete to neovim? appreciate.

### ISSUE THREAD

**Issue by xiaonengmiao** [xywei/dot-files#1]
can you add auto-complete to neovim? appreciate.

**Comment by xywei** [comment]
I already have [deoplete](https://github.com/Shougo/deoplete.nvim) configured. However, autocomplete is disabled as my personal preference. If you want to have auto-complete on, simply change the line 275 in `init.vim` from `let g:deoplete#disable_auto_complete = 1` to `let g:deoplete#disable_auto_complete = 0`.

Alternatively, you can also use `Ctrl-l` to manually complete.

**Comment by xywei** [comment]
Remark: `Ctrl-l` for deoplete  is applicable after 406c161d62754c8409e7ca5270581b22529f4bfb.
