### ISSUE TITLE
Cannot find color scheme 'solarized8_light_flat'

### ISSUE THREAD

**Issue by xiaonengmiao** [xywei/dot-files#2]
报警了!
after pull from origin and open vim i got:
error detected while processing /Users/lihaohan/.config/nvim/init.vim:
line  479:
E185: Cannot find color scheme 'solarized8_light_flat'
Press ENTER or type command to continue
How to fix it?

**Comment by xywei** [comment]
Seems that some plugins are missing. If you can open vim normally after pressing ENTER, try installing missing plugins by running
```vim
:PlugInstall
```
If the issue persists after that, perhaps there are some plugins are outdated. Try updating them by running
```vim
:PlugUpdate | PlugUpgrade
```

**Comment by xiaonengmiao** [comment]
Now I got this:
[chromatica] It requires Neovim with Python3 support("+python3").
zzzz

**Comment by xywei** [comment]
Neovim needs a python package to be installed to use some of the plugins. To install the package, if you have `python3` installed, then just run
```bash
pip3 install neovim
```

**Comment by xywei** [comment]
Assuming that you are on Mac, you may install `python3` using [`homebew`](https://docs.brew.sh/Homebrew-and-Python.html).
```bash
brew install python3
```

**Comment by xiaonengmiao** [comment]
Now it is ok, >^^<
666666666
