### ISSUE TITLE
Promptline is not displayed

### ISSUE THREAD

**Issue by xiaonengmiao** [xywei/dot-files#4]
![image](https://user-images.githubusercontent.com/15117545/39904329-5b220b02-54a5-11e8-99fd-212bb72c6510.png)
![image](https://user-images.githubusercontent.com/15117545/39904358-6a400332-54a5-11e8-9a2b-50894251c330.png)
why the second one dont have the bar above?

**Comment by xywei** [comment]
The prompt line is generated through [vim-airline](https://github.com/vim-airline/vim-airline) integration. See also [promtline.vim](https://github.com/edkolev/promptline.vim).

You need to run both of those vim plugins to generate and keep you prompt line updated.

**Comment by xiaonengmiao** [comment]
how to run vim plugins?

**Comment by xywei** [comment]
It is plugin-specific. Most of the time you can ask it in vim to tell you how by looking at its documentation `:h [plugin_name]`.

**Comment by xiaonengmiao** [comment]
still doesn't work
and also what is this:
![image](https://user-images.githubusercontent.com/15117545/39905449-83e70528-54ab-11e8-93b1-814f7ac5726e.png)

**Comment by xywei** [comment]
I think the error message explains itself pretty clearly: try `:UpdateRemotePlugins`.

**Comment by xiaonengmiao** [comment]
of course I tried it. nothing happened at all

**Comment by xywei** [comment]
If so it is better that you point that out in the first place. Did you check the output of  `:checkhealth` then?

**Comment by xiaonengmiao** [comment]
![image](https://user-images.githubusercontent.com/15117545/39905910-de978d56-54ad-11e8-9ec1-64ee0aa9b733.png)
![image](https://user-images.githubusercontent.com/15117545/39905925-efac3c86-54ad-11e8-926b-cba06d156c79.png)
this is what i got.

**Comment by xiaonengmiao** [comment]
and this what i got when i try: UpdateRemotePlugins
![image](https://user-images.githubusercontent.com/15117545/39906003-3d5fc0e2-54ae-11e8-9736-b1025e8305da.png)

**Comment by xywei** [comment]
I would suggest follow the advice you get there to make at least one of the Python providers work.

**Comment by xiaonengmiao** [comment]
Is there an advice? what advice

**Comment by xywei** [comment]
You might want to look at the screenshots you posted more closely. :)

**Comment by xiaonengmiao** [comment]
I still dont get the idea

**Comment by xywei** [comment]
hint: look for keyword "ADVICE"
