### ISSUE TITLE
tmux 2.9 cause some options in .tmux.conf to fail

### ISSUE THREAD

**Issue by xiaonengmiao** [xywei/dot-files#5]
An update of tmux cause some options in .tmux.conf not working anymore.

refer to this link: https://github.com/tmux/tmux/issues/1691

try to fix it like this:
These are the -style options:
~~~~
             message-command-style style
             message-style style
             mode-style style
             pane-active-border-style style
             pane-border-style style
             status-left-style style
             status-right-style style
             status-style style
             window-active-style style
             window-status-activity-style style
             window-status-bell-style style
             window-status-current-style style
             window-status-last-style style
             window-status-style style
             window-style style
~~~~
The form is exactly the same, it is just one option instead of three:
~~~~
set -g mode-style bg=red,fg=green,blink
~~~~

_Originally posted by @nicm in https://github.com/tmux/tmux/issues/1689#issuecomment-486722349_

**Comment by xywei** [comment]
I haven't been updating this repo lately. Feel free to send a pull request.

Also, checkout [this one](https://github.com/xywei/conforg) if you feel like using Emacs :P.
